name: MP4 to HLS Conversion

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  convert_mp4_to_hls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install ffmpeg
        run: sudo apt-get install ffmpeg -y

      - name: Run HLS conversion script
        run: |
          chmod +x convert_mp4_to_hls.sh
          ./convert_mp4_to_hls.sh input.mp4

      - name: Set up Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Add changes to Git
        run: |
          git add -A
          ls -la

      - name: Commit changes
        run: |
          git commit -m "Add HLS files"
      
      - name: Push changes
        run: |
          git push
