name: Transcode Video

on:
  push:
    branches:
      - main  # Adjust this branch name as needed

jobs:
  transcode:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg
      
    - name: Install requests library
      run: pip install requests
      
    - name: Run Transcoding Script
      run: python transcode_script.py
